import styles from "./page.module.css";

// this page only renders if no hostname is found
// so technically when visiting vercel's autogenerated *.vercel.app domains
export default async function Home() {
  return <div className={styles.page}>NO HOSTNAME PAGE?</div>;
}
