// this page only renders if no hostname is found
// so technically when visiting vercel's autogenerated *.vercel.app domains
// or if you visit something not in process.env.rootDomains

import type { Metadata } from "next";
import {
  HomeLayout,
  CenteredContent,
  FooterContent,
} from "@/components/HomeLayout";
import SignInButton from "@/components/SignInButton";

export const metadata: Metadata = {
  title: "not configured - bluesky-handles-kiosk",
  description: "not ready to take claims yet",
};

export default async function Home() {
  return (
    <HomeLayout hostname="">
      <CenteredContent>
        <h1>not configured!</h1>
        <p>
          <a
            href="https://github.com/zyplos/bluesky-handles-kiosk/wiki/Project-Setup"
            target="_blank"
            rel="noopener"
          >
            zyplos/bluesky-handles-kiosk/wiki/Project-Setup
          </a>
        </p>
      </CenteredContent>
      {process.env.NODE_ENV !== "production" && (
        <FooterContent>
          <SignInButton />
        </FooterContent>
      )}
    </HomeLayout>
  );
}
