// this page only renders if no hostname is found
// so technically when visiting vercel's autogenerated *.vercel.app domains
// or if you visit something not in process.env.rootDomains

import type { Metadata } from "next";
import {
  HomeLayout,
  CenteredContent,
  FooterContent,
} from "@/components/HomeLayout";
import SignInButton from "@/components/SignInButton";

export const metadata: Metadata = {
  title: "not configured - bluesky-handles-kiosk",
  description: "not ready to take claims yet",
};

export default async function Home() {
  return (
    <HomeLayout hostname="">
      <CenteredContent>
        <h1>not configured!</h1>
        <p>zyplos/bluesky-handles-kiosk/wiki/setup</p>
      </CenteredContent>
      {process.env.NODE_ENV !== "production" && (
        <FooterContent>
          <SignInButton />
        </FooterContent>
      )}
    </HomeLayout>
  );
}
